package org.seadva.registry.database.factories.vaRegistry;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.BeanNameAware;

import org.seadva.registry.database.model.dao.vaRegistry.*;

/** 
 * DAO factory implementation.
 * @author autogenerated
 */
@Component
public class HibernateVaRegistryDaoFactory implements ApplicationContextAware, BeanNameAware {
	/** Placeholder for an instance. */
	private static HibernateVaRegistryDaoFactory instance;
	/** Internal state. */
	private static ApplicationContext context = null;
	/** Bean Name. */
	private static String beanName;

	/** Return an instance of this class.
	 * @return an instance of this class
	 */
	public static synchronized HibernateVaRegistryDaoFactory getInstance() {
		if (instance == null) {
			instance = (HibernateVaRegistryDaoFactory) context.getBean(beanName);
		}
		return instance;
	}

	/**
	 * Sets a Spring Application Context object.
  	 * @param ctxt ApplicationContext to set
	 * @throws org.springframework.beans.BeansException on spring error
	 */
	@Autowired
	public void setApplicationContext(ApplicationContext ctxt)
			throws BeansException 
	{
		context = ctxt;
	}

	/**
	* 
	* {@inheritDoc}
	* 
	* @see org.springframework.beans.factory.BeanNameAware#setBeanName(String)
	*/
	public void setBeanName(String name) {
		beanName = name;
	}

	/**
	 * Return the requested bean from the context, throwing a RuntimeException on error.
	 *
	 * @param beanName to return
	 * @return the bean requested.
	 */
	public static Object getBean(String beanName) {
		Object result = context.getBean(beanName);
		if (result == null) { 
			throw new IllegalStateException(String.format("Could not find bean '%s'. Did you set the right component scanning?", beanName));
		} 
		
		return result;
	}

	
	/**
	 * Returns a AgentDao instance.
	 * 
	 * @return a AgentDao instance
	 */
	public static AgentDao getAgentDao() {
		return (AgentDao) getBean("agentDaoImpl"); 
	}
	/**
	 * Returns a AgentProfileDao instance.
	 * 
	 * @return a AgentProfileDao instance
	 */
	public static AgentProfileDao getAgentProfileDao() {
		return (AgentProfileDao) getBean("agentProfileDaoImpl"); 
	}
	/**
	 * Returns a AgentRoleDao instance.
	 * 
	 * @return a AgentRoleDao instance
	 */
	public static AgentRoleDao getAgentRoleDao() {
		return (AgentRoleDao) getBean("agentRoleDaoImpl"); 
	}
	/**
	 * Returns a AggregationDao instance.
	 * 
	 * @return a AggregationDao instance
	 */
	public static AggregationDao getAggregationDao() {
		return (AggregationDao) getBean("aggregationDaoImpl"); 
	}
	/**
	 * Returns a BaseEntityDao instance.
	 * 
	 * @return a BaseEntityDao instance
	 */
	public static BaseEntityDao getBaseEntityDao() {
		return (BaseEntityDao) getBean("baseEntityDaoImpl"); 
	}
	/**
	 * Returns a CollectionDao instance.
	 * 
	 * @return a CollectionDao instance
	 */
	public static CollectionDao getCollectionDao() {
		return (CollectionDao) getBean("collectionDaoImpl"); 
	}
	/**
	 * Returns a DataIdentifierDao instance.
	 * 
	 * @return a DataIdentifierDao instance
	 */
	public static DataIdentifierDao getDataIdentifierDao() {
		return (DataIdentifierDao) getBean("dataIdentifierDaoImpl"); 
	}
	/**
	 * Returns a DataIdentifierTypeDao instance.
	 * 
	 * @return a DataIdentifierTypeDao instance
	 */
	public static DataIdentifierTypeDao getDataIdentifierTypeDao() {
		return (DataIdentifierTypeDao) getBean("dataIdentifierTypeDaoImpl"); 
	}
	/**
	 * Returns a DataLocationDao instance.
	 * 
	 * @return a DataLocationDao instance
	 */
	public static DataLocationDao getDataLocationDao() {
		return (DataLocationDao) getBean("dataLocationDaoImpl"); 
	}
	/**
	 * Returns a EntityContentDao instance.
	 * 
	 * @return a EntityContentDao instance
	 */
	public static EntityContentDao getEntityContentDao() {
		return (EntityContentDao) getBean("entityContentDaoImpl"); 
	}
	/**
	 * Returns a EntityTypeDao instance.
	 * 
	 * @return a EntityTypeDao instance
	 */
	public static EntityTypeDao getEntityTypeDao() {
		return (EntityTypeDao) getBean("entityTypeDaoImpl"); 
	}
	/**
	 * Returns a EventDao instance.
	 * 
	 * @return a EventDao instance
	 */
	public static EventDao getEventDao() {
		return (EventDao) getBean("eventDaoImpl"); 
	}
	/**
	 * Returns a EventTypeDao instance.
	 * 
	 * @return a EventTypeDao instance
	 */
	public static EventTypeDao getEventTypeDao() {
		return (EventTypeDao) getBean("eventTypeDaoImpl"); 
	}
	/**
	 * Returns a FileDao instance.
	 * 
	 * @return a FileDao instance
	 */
	public static FileDao getFileDao() {
		return (FileDao) getBean("fileDaoImpl"); 
	}
	/**
	 * Returns a FixityDao instance.
	 * 
	 * @return a FixityDao instance
	 */
	public static FixityDao getFixityDao() {
		return (FixityDao) getBean("fixityDaoImpl"); 
	}
	/**
	 * Returns a FormatDao instance.
	 * 
	 * @return a FormatDao instance
	 */
	public static FormatDao getFormatDao() {
		return (FormatDao) getBean("formatDaoImpl"); 
	}
	/**
	 * Returns a MetadataReferenceDao instance.
	 * 
	 * @return a MetadataReferenceDao instance
	 */
	public static MetadataReferenceDao getMetadataReferenceDao() {
		return (MetadataReferenceDao) getBean("metadataReferenceDaoImpl"); 
	}
	/**
	 * Returns a MetadataTypeDao instance.
	 * 
	 * @return a MetadataTypeDao instance
	 */
	public static MetadataTypeDao getMetadataTypeDao() {
		return (MetadataTypeDao) getBean("metadataTypeDaoImpl"); 
	}
	/**
	 * Returns a ProfileTypeDao instance.
	 * 
	 * @return a ProfileTypeDao instance
	 */
	public static ProfileTypeDao getProfileTypeDao() {
		return (ProfileTypeDao) getBean("profileTypeDaoImpl"); 
	}
	/**
	 * Returns a PropertyDao instance.
	 * 
	 * @return a PropertyDao instance
	 */
	public static PropertyDao getPropertyDao() {
		return (PropertyDao) getBean("propertyDaoImpl"); 
	}
	/**
	 * Returns a RelationDao instance.
	 * 
	 * @return a RelationDao instance
	 */
	public static RelationDao getRelationDao() {
		return (RelationDao) getBean("relationDaoImpl"); 
	}
	/**
	 * Returns a RelationTypeDao instance.
	 * 
	 * @return a RelationTypeDao instance
	 */
	public static RelationTypeDao getRelationTypeDao() {
		return (RelationTypeDao) getBean("relationTypeDaoImpl"); 
	}
	/**
	 * Returns a RepositoryDao instance.
	 * 
	 * @return a RepositoryDao instance
	 */
	public static RepositoryDao getRepositoryDao() {
		return (RepositoryDao) getBean("repositoryDaoImpl"); 
	}
	/**
	 * Returns a RoleTypeDao instance.
	 * 
	 * @return a RoleTypeDao instance
	 */
	public static RoleTypeDao getRoleTypeDao() {
		return (RoleTypeDao) getBean("roleTypeDaoImpl"); 
	}
	/**
	 * Returns a StateDao instance.
	 * 
	 * @return a StateDao instance
	 */
	public static StateDao getStateDao() {
		return (StateDao) getBean("stateDaoImpl"); 
	}
	/**
	 * Returns a TransitionDao instance.
	 * 
	 * @return a TransitionDao instance
	 */
	public static TransitionDao getTransitionDao() {
		return (TransitionDao) getBean("transitionDaoImpl"); 
	}

}
