package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.AgentRolePK;
import java.io.Serializable;
/**
 * DAO interface for table: AgentRolePK.
 * @author autogenerated
 */
public interface AgentRolePKDao extends GenericDAO<AgentRolePK,  Serializable>  {
	// constructor only
}

