package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.AgentRole;
import org.seadva.registry.database.model.obj.vaRegistry.AgentRolePK;
/**
 * DAO interface for table: AgentRole.
 * @author autogenerated
 */
public interface AgentRoleDao extends GenericDAO<AgentRole,  AgentRolePK>  {
	// constructor only
}

