package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.AgentProfile;
import org.seadva.registry.database.model.obj.vaRegistry.AgentProfilePK;
/**
 * DAO interface for table: AgentProfile.
 * @author autogenerated
 */
public interface AgentProfileDao extends GenericDAO<AgentProfile,  AgentProfilePK>  {
	// constructor only
}

