package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.AgentProfilePK;
import java.io.Serializable;
/**
 * DAO interface for table: AgentProfilePK.
 * @author autogenerated
 */
public interface AgentProfilePKDao extends GenericDAO<AgentProfilePK,  Serializable>  {
	// constructor only
}

