package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.Agent;
 
/**
 * DAO interface for table: Agent.
 * @author autogenerated
 */
public interface AgentDao extends GenericDAO<Agent,  String>  {
	// constructor only
}

