package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.Aggregation;
import org.seadva.registry.database.model.obj.vaRegistry.AggregationPK;
import org.springframework.transaction.annotation.Transactional;

/**
 * DAO interface for table: Aggregation.
 * @author autogenerated
 */
@Transactional
public interface AggregationDao extends GenericDAO<Aggregation,  AggregationPK>  {
	// constructor only
}

