package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.AggregationPK;
import java.io.Serializable;
/**
 * DAO interface for table: AggregationPK.
 * @author autogenerated
 */
public interface AggregationPKDao extends GenericDAO<AggregationPK,  Serializable>  {
	// constructor only
}

