package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.BaseEntity;
 
/**
 * DAO interface for table: BaseEntity.
 * @author autogenerated
 */
public interface BaseEntityDao extends GenericDAO<BaseEntity,  String>  {
	// constructor only
}

