package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.Collection;
 
/**
 * DAO interface for table: Collection.
 * @author autogenerated
 */
public interface CollectionDao extends GenericDAO<Collection,  String>  {
	// constructor only
}

