package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.DataIdentifier;
import org.seadva.registry.database.model.obj.vaRegistry.DataIdentifierPK;
/**
 * DAO interface for table: DataIdentifier.
 * @author autogenerated
 */
public interface DataIdentifierDao extends GenericDAO<DataIdentifier,  DataIdentifierPK>  {
	// constructor only
}

