package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.DataLocation;
import org.seadva.registry.database.model.obj.vaRegistry.DataLocationPK;
/**
 * DAO interface for table: DataLocation.
 * @author autogenerated
 */
public interface DataLocationDao extends GenericDAO<DataLocation,  DataLocationPK>  {
	// constructor only
}

