package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.DataLocationPK;
import java.io.Serializable;
/**
 * DAO interface for table: DataLocationPK.
 * @author autogenerated
 */
public interface DataLocationPKDao extends GenericDAO<DataLocationPK,  Serializable>  {
	// constructor only
}

