package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.DataIdentifierType;
 
/**
 * DAO interface for table: DataIdentifierType.
 * @author autogenerated
 */
public interface DataIdentifierTypeDao extends GenericDAO<DataIdentifierType,  String>  {
	// constructor only
}

