package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.DataIdentifierPK;
import java.io.Serializable;
/**
 * DAO interface for table: DataIdentifierPK.
 * @author autogenerated
 */
public interface DataIdentifierPKDao extends GenericDAO<DataIdentifierPK,  Serializable>  {
	// constructor only
}

