package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.EntityContent;
 
/**
 * DAO interface for table: EntityContent.
 * @author autogenerated
 */
public interface EntityContentDao extends GenericDAO<EntityContent,  Integer>  {
	// constructor only
}

