package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.EntityTypePK;
import java.io.Serializable;
/**
 * DAO interface for table: EntityTypePK.
 * @author autogenerated
 */
public interface EntityTypePKDao extends GenericDAO<EntityTypePK,  Serializable>  {
	// constructor only
}

