package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.EntityType;
import org.seadva.registry.database.model.obj.vaRegistry.EntityTypePK;
/**
 * DAO interface for table: EntityType.
 * @author autogenerated
 */
public interface EntityTypeDao extends GenericDAO<EntityType,  EntityTypePK>  {
	// constructor only
}

