package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.Event;
 
/**
 * DAO interface for table: Event.
 * @author autogenerated
 */
public interface EventDao extends GenericDAO<Event,  String>  {
	// constructor only
}

