package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.EventType;
 
/**
 * DAO interface for table: EventType.
 * @author autogenerated
 */
public interface EventTypeDao extends GenericDAO<EventType,  String>  {
	// constructor only
}

