package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.File;
 
/**
 * DAO interface for table: File.
 * @author autogenerated
 */
public interface FileDao extends GenericDAO<File,  String>  {
	// constructor only
}

