package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.FixityPK;
import java.io.Serializable;
/**
 * DAO interface for table: FixityPK.
 * @author autogenerated
 */
public interface FixityPKDao extends GenericDAO<FixityPK,  Serializable>  {
	// constructor only
}

