package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.Fixity;
import org.seadva.registry.database.model.obj.vaRegistry.FixityPK;
/**
 * DAO interface for table: Fixity.
 * @author autogenerated
 */
public interface FixityDao extends GenericDAO<Fixity,  FixityPK>  {
	// constructor only
}

