package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.Format;
 
/**
 * DAO interface for table: Format.
 * @author autogenerated
 */
public interface FormatDao extends GenericDAO<Format,  Long>  {
	// constructor only
}

