package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.MetadataType;
 
/**
 * DAO interface for table: MetadataType.
 * @author autogenerated
 */
public interface MetadataTypeDao extends GenericDAO<MetadataType,  String>  {
	// constructor only
}

