package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.MetadataReference;
 
/**
 * DAO interface for table: MetadataReference.
 * @author autogenerated
 */
public interface MetadataReferenceDao extends GenericDAO<MetadataReference,  Long>  {
	// constructor only
}

