package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.ProfileType;
 
/**
 * DAO interface for table: ProfileType.
 * @author autogenerated
 */
public interface ProfileTypeDao extends GenericDAO<ProfileType,  String>  {
	// constructor only
}

