package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.Property;
 
/**
 * DAO interface for table: Property.
 * @author autogenerated
 */
public interface PropertyDao extends GenericDAO<Property,  Long>  {
	// constructor only
}

