package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.RelationType;
 
/**
 * DAO interface for table: RelationType.
 * @author autogenerated
 */
public interface RelationTypeDao extends GenericDAO<RelationType,  String>  {
	// constructor only
}

