package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.RelationPK;
import java.io.Serializable;
/**
 * DAO interface for table: RelationPK.
 * @author autogenerated
 */
public interface RelationPKDao extends GenericDAO<RelationPK,  Serializable>  {
	// constructor only
}

