package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.Relation;
import org.seadva.registry.database.model.obj.vaRegistry.RelationPK;
/**
 * DAO interface for table: Relation.
 * @author autogenerated
 */
public interface RelationDao extends GenericDAO<Relation,  RelationPK>  {
	// constructor only
}

