package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.Repository;
 
/**
 * DAO interface for table: Repository.
 * @author autogenerated
 */
public interface RepositoryDao extends GenericDAO<Repository,  String>  {
	// constructor only
}

