package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.RoleType;
 
/**
 * DAO interface for table: RoleType.
 * @author autogenerated
 */
public interface RoleTypeDao extends GenericDAO<RoleType,  String>  {
	// constructor only
}

