package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.State;
 
/**
 * DAO interface for table: State.
 * @author autogenerated
 */
public interface StateDao extends GenericDAO<State,  String>  {
	// constructor only
}

