package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.TransitionPK;
import java.io.Serializable;
/**
 * DAO interface for table: TransitionPK.
 * @author autogenerated
 */
public interface TransitionPKDao extends GenericDAO<TransitionPK,  Serializable>  {
	// constructor only
}

