package org.seadva.registry.database.model.dao.vaRegistry;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.seadva.registry.database.model.obj.vaRegistry.Transition;
import org.seadva.registry.database.model.obj.vaRegistry.TransitionPK;
/**
 * DAO interface for table: Transition.
 * @author autogenerated
 */
public interface TransitionDao extends GenericDAO<Transition,  TransitionPK>  {
	// constructor only
}

