package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.apache.log4j.Logger;
import org.seadva.registry.database.common.DBConnectionPool;
import org.seadva.registry.database.common.ObjectPool;
import org.seadva.registry.database.model.dao.vaRegistry.AgentDao;
import org.seadva.registry.database.model.dao.vaRegistry.AgentProfileDao;
import org.seadva.registry.database.model.dao.vaRegistry.AgentRoleDao;
import org.seadva.registry.database.model.obj.vaRegistry.*;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;


/**
 * DAO for table: Agent.
 * @author autogenerated
 */

public class AgentDaoImpl implements AgentDao {

    private static Logger log = Logger.getLogger(AgentDaoImpl.class);

    protected Connection getConnection() throws SQLException {
        return connectionPool.getEntry();
    }

    protected ObjectPool<Connection> connectionPool = null;
    AgentRoleDao agentRoleDao;
    AgentProfileDao agentProfileDao;

    public AgentDaoImpl(){
        connectionPool = DBConnectionPool.getInstance();
        agentRoleDao = new AgentRoleDaoImpl();
        agentProfileDao = new AgentProfileDaoImpl();
    }

    @Override
    public boolean putAgent(Agent agent) {

        for(AgentRole role: agent.getAgentRoles()){
            agentRoleDao.putAgentRole(role);
        }

        for(AgentProfile profile: agent.getAgentProfiles()){
            agentProfileDao.putAgentProfile(profile);
        }

        Connection connection = null;
        PreparedStatement statement = null;
        try {
            connection = getConnection();
            statement = connection.prepareStatement("INSERT INTO agent values(?,?,?)");
            statement.setString(1, agent.getId());
            statement.setString(2, agent.getFirstName());
            statement.setString(3, agent.getLastName());
            statement.executeUpdate();

            statement.close();
            log.debug("Done resetting unfinished raw notifications");
        } catch (SQLException sqle) {
            throw new RuntimeException(sqle);
        } finally {
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    log.warn("Unable to close statement", e);
                }
                statement = null;
            }
            connectionPool.releaseEntry(connection);

        }

        return true;

    }
}

