package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.AgentProfilePK;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.AgentProfilePKDao;
import java.io.Serializable;
 
/**
 * DAO for table: AgentProfilePK.
 * @author autogenerated
 */
@Repository
public class AgentProfilePKDaoImpl extends GenericHibernateDaoImpl<AgentProfilePK, Serializable> implements AgentProfilePKDao {
	
	/** Constructor method. */
		public AgentProfilePKDaoImpl() {
			super(AgentProfilePK.class);
		}
	}

