package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.AgentProfile;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.AgentProfileDao;
import org.seadva.registry.database.model.obj.vaRegistry.AgentProfilePK;
 
/**
 * DAO for table: AgentProfile.
 * @author autogenerated
 */
@Repository
public class AgentProfileDaoImpl extends GenericHibernateDaoImpl<AgentProfile, AgentProfilePK> implements AgentProfileDao {
	
	/** Constructor method. */
		public AgentProfileDaoImpl() {
			super(AgentProfile.class);
		}
	}

