package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.AggregationPK;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.AggregationPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: AggregationPK.
 * @author autogenerated
 */
@Repository
public class AggregationPKDaoImpl extends GenericHibernateDaoImpl<AggregationPK, Serializable> implements AggregationPKDao {
	
	/** Constructor method. */
		public AggregationPKDaoImpl() {
			super(AggregationPK.class);
		}
	}

