package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.Collection;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.CollectionDao;
 
 
/**
 * DAO for table: Collection.
 * @author autogenerated
 */
@Repository
public class CollectionDaoImpl extends GenericHibernateDaoImpl<Collection, String> implements CollectionDao {
	
	/** Constructor method. */
		public CollectionDaoImpl() {
			super(Collection.class);
		}
	}

