package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.DataIdentifier;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.DataIdentifierDao;
import org.seadva.registry.database.model.obj.vaRegistry.DataIdentifierPK;
 
/**
 * DAO for table: DataIdentifier.
 * @author autogenerated
 */
@Repository
public class DataIdentifierDaoImpl extends GenericHibernateDaoImpl<DataIdentifier, DataIdentifierPK> implements DataIdentifierDao {
	
	/** Constructor method. */
		public DataIdentifierDaoImpl() {
			super(DataIdentifier.class);
		}
	}

