package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.DataLocationPK;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.DataLocationPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: DataLocationPK.
 * @author autogenerated
 */
@Repository
public class DataLocationPKDaoImpl extends GenericHibernateDaoImpl<DataLocationPK, Serializable> implements DataLocationPKDao {
	
	/** Constructor method. */
		public DataLocationPKDaoImpl() {
			super(DataLocationPK.class);
		}
	}

