package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.EntityTypePK;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.EntityTypePKDao;
import java.io.Serializable;
 
/**
 * DAO for table: EntityTypePK.
 * @author autogenerated
 */
@Repository
public class EntityTypePKDaoImpl extends GenericHibernateDaoImpl<EntityTypePK, Serializable> implements EntityTypePKDao {
	
	/** Constructor method. */
		public EntityTypePKDaoImpl() {
			super(EntityTypePK.class);
		}
	}

