package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.EntityContent;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.EntityContentDao;
 
 
/**
 * DAO for table: EntityContent.
 * @author autogenerated
 */
@Repository
public class EntityContentDaoImpl extends GenericHibernateDaoImpl<EntityContent, Integer> implements EntityContentDao {
	
	/** Constructor method. */
		public EntityContentDaoImpl() {
			super(EntityContent.class);
		}
	}

