package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.EventType;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.EventTypeDao;
 
 
/**
 * DAO for table: EventType.
 * @author autogenerated
 */
@Repository
public class EventTypeDaoImpl extends GenericHibernateDaoImpl<EventType, String> implements EventTypeDao {
	
	/** Constructor method. */
		public EventTypeDaoImpl() {
			super(EventType.class);
		}
	}

