package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.File;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.FileDao;
 
 
/**
 * DAO for table: File.
 * @author autogenerated
 */
@Repository
public class FileDaoImpl extends GenericHibernateDaoImpl<File, String> implements FileDao {
	
	/** Constructor method. */
		public FileDaoImpl() {
			super(File.class);
		}
	}

