package org.seadva.registry.database.model.dao.vaRegistry.impl;

import org.apache.log4j.Logger;
import org.seadva.registry.database.common.DBConnectionPool;
import org.seadva.registry.database.common.ObjectPool;
import org.seadva.registry.database.model.dao.vaRegistry.BaseEntityDao;
import org.seadva.registry.database.model.dao.vaRegistry.FileDao;
import org.seadva.registry.database.model.obj.vaRegistry.BaseEntity;
import org.seadva.registry.database.model.obj.vaRegistry.File;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 * DAO for table: File.
 * @author autogenerated
 */

public class FileDaoImpl implements FileDao {
    protected Connection getConnection() throws SQLException {
        return connectionPool.getEntry();
    }
    public FileDaoImpl(){
        connectionPool = DBConnectionPool.getInstance();
        baseEntityDao = new BaseEntityDaoImpl();
    }
    private static Logger log = Logger.getLogger(FileDaoImpl.class);
    BaseEntityDao baseEntityDao;
    protected ObjectPool<Connection> connectionPool = null;

    @Override
    public File getFile(String entityId) {
        BaseEntity entity = new BaseEntityDaoImpl().getBaseEntity(entityId);
        File file = new File(entity);
        Connection connection = null;
        PreparedStatement statement = null;

        try {
            connection = getConnection();

            statement = connection.prepareStatement("Select * from collection where entity_id=?");
            statement.setString(1, entityId);
            ResultSet resultSet = statement.executeQuery();


            while (resultSet.next()) {
                file.setFileName(resultSet.getString("file_name"));
                file.setIsObsolete(resultSet.getInt("is_obsolete"));
                file.setSizeBytes(resultSet.getLong("size_bytes"));
                break;
            }


        } catch (SQLException sqle) {
            throw new RuntimeException(sqle);
        } finally {
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    //  log.warn("Unable to close statement", e);
                }
                statement = null;
            }
            connectionPool.releaseEntry(connection);

        }
        return file;
    }

    @Override
    public boolean insertFile(File file) {

        Connection connection = null;
        PreparedStatement statement = null;
        try {
            connection = getConnection();
            statement = connection.prepareStatement("INSERT INTO file (entity_id, file_name, size_bytes, version_num) values(?,?,?,?)");
            statement.setString(1, file.getId());
            String fileName = file.getFileName();
            if(fileName==null)
                fileName = file.getEntityName();

            statement.setString(2, fileName);
            if(file.getSizeBytes()==null)
                statement.setLong(3,-1);
            else
                statement.setLong(3, file.getSizeBytes());
            String versionNum = "1";
            if(file.getVersionNum()!=null)
                versionNum = file.getVersionNum();
            statement.setString(4,versionNum);
            statement.executeUpdate();
            statement.close();
            baseEntityDao.insertEntity(file);
            log.debug("Done resetting unfinished raw notifications");
        } catch (SQLException sqle) {
            throw new RuntimeException(sqle);
        } finally {
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    log.warn("Unable to close statement", e);
                }
                statement = null;
            }
            connectionPool.releaseEntry(connection);

        }

        return true;

    }

}

