package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.FixityPK;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.FixityPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: FixityPK.
 * @author autogenerated
 */
@Repository
public class FixityPKDaoImpl extends GenericHibernateDaoImpl<FixityPK, Serializable> implements FixityPKDao {
	
	/** Constructor method. */
		public FixityPKDaoImpl() {
			super(FixityPK.class);
		}
	}

