package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.Fixity;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.FixityDao;
import org.seadva.registry.database.model.obj.vaRegistry.FixityPK;
 
/**
 * DAO for table: Fixity.
 * @author autogenerated
 */
@Repository
public class FixityDaoImpl extends GenericHibernateDaoImpl<Fixity, FixityPK> implements FixityDao {
	
	/** Constructor method. */
		public FixityDaoImpl() {
			super(Fixity.class);
		}
	}

