package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.Format;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.FormatDao;
 
 
/**
 * DAO for table: Format.
 * @author autogenerated
 */
@Repository
public class FormatDaoImpl extends GenericHibernateDaoImpl<Format, Long> implements FormatDao {
	
	/** Constructor method. */
		public FormatDaoImpl() {
			super(Format.class);
		}
	}

