package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.MetadataReference;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.MetadataReferenceDao;
 
 
/**
 * DAO for table: MetadataReference.
 * @author autogenerated
 */
@Repository
public class MetadataReferenceDaoImpl extends GenericHibernateDaoImpl<MetadataReference, Long> implements MetadataReferenceDao {
	
	/** Constructor method. */
		public MetadataReferenceDaoImpl() {
			super(MetadataReference.class);
		}
	}

