package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.MetadataType;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.MetadataTypeDao;
 
 
/**
 * DAO for table: MetadataType.
 * @author autogenerated
 */
@Repository
public class MetadataTypeDaoImpl extends GenericHibernateDaoImpl<MetadataType, String> implements MetadataTypeDao {
	
	/** Constructor method. */
		public MetadataTypeDaoImpl() {
			super(MetadataType.class);
		}
	}

