package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.ProfileType;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.ProfileTypeDao;
 
 
/**
 * DAO for table: ProfileType.
 * @author autogenerated
 */
@Repository
public class ProfileTypeDaoImpl extends GenericHibernateDaoImpl<ProfileType, String> implements ProfileTypeDao {
	
	/** Constructor method. */
		public ProfileTypeDaoImpl() {
			super(ProfileType.class);
		}
	}

