package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.Property;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.PropertyDao;
 
 
/**
 * DAO for table: Property.
 * @author autogenerated
 */
@Repository
public class PropertyDaoImpl extends GenericHibernateDaoImpl<Property, Long> implements PropertyDao {
	
	/** Constructor method. */
		public PropertyDaoImpl() {
			super(Property.class);
		}
	}

