package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.RelationType;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.RelationTypeDao;
 
 
/**
 * DAO for table: RelationType.
 * @author autogenerated
 */
@Repository
public class RelationTypeDaoImpl extends GenericHibernateDaoImpl<RelationType, String> implements RelationTypeDao {
	
	/** Constructor method. */
		public RelationTypeDaoImpl() {
			super(RelationType.class);
		}
	}

