package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.Relation;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.RelationDao;
import org.seadva.registry.database.model.obj.vaRegistry.RelationPK;
 
/**
 * DAO for table: Relation.
 * @author autogenerated
 */
@Repository
public class RelationDaoImpl extends GenericHibernateDaoImpl<Relation, RelationPK> implements RelationDao {
	
	/** Constructor method. */
		public RelationDaoImpl() {
			super(Relation.class);
		}
	}

