package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.RelationPK;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.RelationPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: RelationPK.
 * @author autogenerated
 */
@Repository
public class RelationPKDaoImpl extends GenericHibernateDaoImpl<RelationPK, Serializable> implements RelationPKDao {
	
	/** Constructor method. */
		public RelationPKDaoImpl() {
			super(RelationPK.class);
		}
	}

