package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.RepositoryDao;
 
 
/**
 * DAO for table: Repository.
 * @author autogenerated
 */
@Repository
public class RepositoryDaoImpl extends GenericHibernateDaoImpl<org.seadva.registry.database.model.obj.vaRegistry.Repository, String> implements RepositoryDao {
	
	/** Constructor method. */
		public RepositoryDaoImpl() {
			super(org.seadva.registry.database.model.obj.vaRegistry.Repository.class);
		}
	}

