package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.RoleType;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.RoleTypeDao;
 
 
/**
 * DAO for table: RoleType.
 * @author autogenerated
 */
@Repository
public class RoleTypeDaoImpl extends GenericHibernateDaoImpl<RoleType, String> implements RoleTypeDao {
	
	/** Constructor method. */
		public RoleTypeDaoImpl() {
			super(RoleType.class);
		}
	}

