package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.State;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.StateDao;
 
 
/**
 * DAO for table: State.
 * @author autogenerated
 */
@Repository
public class StateDaoImpl extends GenericHibernateDaoImpl<State, String> implements StateDao {
	
	/** Constructor method. */
		public StateDaoImpl() {
			super(State.class);
		}
	}

