package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.TransitionPK;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.TransitionPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: TransitionPK.
 * @author autogenerated
 */
@Repository
public class TransitionPKDaoImpl extends GenericHibernateDaoImpl<TransitionPK, Serializable> implements TransitionPKDao {
	
	/** Constructor method. */
		public TransitionPKDaoImpl() {
			super(TransitionPK.class);
		}
	}

