package org.seadva.registry.database.model.dao.vaRegistry.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.seadva.registry.database.model.obj.vaRegistry.Transition;
import org.springframework.stereotype.Repository;
import org.seadva.registry.database.model.dao.vaRegistry.TransitionDao;
import org.seadva.registry.database.model.obj.vaRegistry.TransitionPK;
 
/**
 * DAO for table: Transition.
 * @author autogenerated
 */
@Repository
public class TransitionDaoImpl extends GenericHibernateDaoImpl<Transition, TransitionPK> implements TransitionDao {
	
	/** Constructor method. */
		public TransitionDaoImpl() {
			super(Transition.class);
		}
	}

