<%@ taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jstl/fmt" %>
<%@ taglib prefix="fmt_rt" uri="http://java.sun.com/jstl/fmt_rt" %>

<%--
  ~ Copyright 2012 Johns Hopkins University
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  --%>
<script type="text/javascript">

    <%--
        A Java Map<String, List<DcsMetadataFormat>>; keys lists of DcsMetadataFormats by their
        associated discipline identifier
    --%>
    <c:set var="mdfDisciplineMap" value="${actionBean.metadataFormatsWithDiscipline}"/>

    <%--
        A JSON object which maps discipline identifiers to metadata formats:

        "discplineId1" : [
            { "formatId" : "an id",
                "name" : "a format name" },
            { "formatId" : "another id",
                "name" : "another name"}
        ],

        "disciplineId2 : [
            { "formatId" : "an id",
                "name" : "a format name" },
            { "formatId" : "another id",
                "name" : "another name"}
        ],

        ...

    --%>
    var disciplineToMetadataFormatMap = {
        <c:forEach var="discipline" items="${actionBean.disciplines}">
            <c:out escapeXml="false" value='"${discipline.id}" : ['/>
            <c:out value="
            "/>
            <c:forEach var="format" items="${mdfDisciplineMap[discipline.id]}">
                <c:out escapeXml="false" value='{  "formatId" : "${format.id}",'/>
                <c:out value="
                "/>
                <c:out escapeXml="false" value='  "name" : "${format.name}" },'/>
            </c:forEach>
            <c:out value=' ],'/>
            <c:out value="
            "/>
        </c:forEach>
    };

    <%--
        Produces a select box of possible formats, given a discipline id.  The function uses the
        disciplineToMetadataFormatMap structure to create and populate a &lt;select> box.  The generated HTML is
        then set on the innerHtml property of the &lt;span> element with an id of 'mf_format_select_box'; essentially
        that span tag acts as a placeholder for the HTML generated by this function.
    --%>
    function produceFormatSelectBox(selectedDisciplineId) {
        var formats = disciplineToMetadataFormatMap[selectedDisciplineId];

        var html = "<select name='metadataFile.metadataFormatId' id='format-select-id-'" + selectedDisciplineId + "'>\n";

        if (formats.length > 0) {
            for (var i = 0; i < formats.length ; i++) {
                html += "  <option value='" + formats[i].formatId + "'>" + formats[i].name + "</option>\n";
            }
        } else {
            html += "  <option selected value='dc:discipline:None'>None</option>";
        }

        html += "</select>";

        document.getElementById("mf_format_select_box").innerHTML = html;
    }

    <%--
        Simply invokes produceFormatSelectBox(...)
    --%>
	function selectFormatList(selectedFormat) {
        produceFormatSelectBox(selectedFormat);
	}
	
	function updateNameField(uploadedFile) {
		var parts = uploadedFile.value.split("\\");
		var parts2 = uploadedFile.value.split("\/");
		if (document.getElementById("filename").value.length == 0 ) {
			if (parts.length > 1) {
				var n = parts.pop();
				document.getElementById("filename").value=n;
			}
			else if (parts2.length > 1) {
				var n = parts2.pop();
				alert(n);
				document.getElementById("filename").value=n;
			}
			else {
				document.getElementById("filename").value=uploadedFile.value;
			}
		}
    }

	function previewIngest(previewMessage) {
	    alert(previewMessage);
	}


	
</script>

<stripes:layout-render name="/layout/${requestScope['stripes_layout']}/layout.jsp">
    <stripes:layout-component name="contents">

        <h2 class="SectionHeader">Adding collection metadata file</h2>
     		<div class="SectionContent">
            <stripes:form beanclass="org.dataconservancy.ui.stripes.MetadataFileActionBean" class="CollectionMetadataFileForm">
                <!-- 
                <p>
                    <fmt_rt:bundle basename="StripesResources" prefix="${actionBean.class.name}.">
                            <fmt:message key="formLabel"/>
                    </fmt_rt:bundle>
                </p>
                -->
                
                <fieldset>
                    <div class="content-left-col">
                        <div class="label-field-group">
                            <stripes:label name="name" for="mf_name"/>
                            <stripes:text id="filename" name="metadataFile.name"/>
                            <stripes:errors field="metadataFile.name"/>
                        </div>
                        <stripes:text name="parentID" style="display:none"/>
                        <stripes:text name="redirectUrl" style="display:none"/>
                        <c:if test="${!empty actionBean.metadataFileID}">
                        	<div class="label-field-group">
	                        	<stripes:text name="metadataFile.source" style="display:none"/>
	                        	<stripes:text name="metadataFileID" style="display:none"/>
                        	</div>
                        </c:if>
                        <div class="label-field-group">
                            <stripes:label name="file" for="mf_file"/>
                            <stripes:file name="uploadedFile" onchange="updateNameField(uploadedFile)"/>
                            <stripes:errors field="uploadedFile"/>
                        </div>
                        <div class="label-field-group">
                            <stripes:label name="discipline" for="mf_discipline"/>
                            <%-- selectFormatList(...) is provided the selected discipline identifier, and invokes
                                 'produceFormatSelectBox' which sets the innerHtml property of the span element
                                 below. --%>
                            <stripes:select name="discipline" id="disciplineSelect"
                                            onchange="selectFormatList(this.value)" value="dc:discipline:None">
                            	<stripes:options-collection collection="${actionBean.disciplines}" value="id" label="title" />
                    	    </stripes:select>
                        </div>
                        <div class="label-field-group">
                            <stripes:label name="format" for="mf_format"/>

                            <%-- The span element is populated by the javascript function 'produceFormatSelectBox';
                                 Essentially this span tag functions as a placeholder for HTML generated and set by the
                                 'produceFormatSelectBox' function --%>
                            <span id="mf_format_select_box">
                                <select id="dc:discipline:None">
                                    <option value="none">None</option>
                                </select>
                            </span>
                        </div>
                        <div class="content-left-col">
                        	If you can't find the format you are looking for please contact your system administrator.
                        </div>
                    </div>
                </fieldset>

                <fieldset>
                    <fmt_rt:bundle basename="pageText/metadata" prefix="metadata.">
                        <fmt:message key="ingestPreviewMessage" var="previewMessage"/>
                    </fmt_rt:bundle>
                    <div>
                        <stripes:submit name="previewMetadataIngest" value="Preview"/>
                         <stripes:submit name="cancel" value="Cancel"/>
                    </div>
                </fieldset>
            </stripes:form>
            </div>
   
   
    </stripes:layout-component>
</stripes:layout-render>
