---
--- Copyright 2012 Johns Hopkins University
---
--- Licensed under the Apache License, Version 2.0 (the "License");
--- you may not use this file except in compliance with the License.
--- You may obtain a copy of the License at
---
---     http://www.apache.org/licenses/LICENSE-2.0
---
--- Unless required by applicable law or agreed to in writing, software
--- distributed under the License is distributed on an "AS IS" BASIS,
--- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--- See the License for the specific language governing permissions and
--- limitations under the License.
---
CREATE TABLE PERSON (ID VARCHAR(1024) PRIMARY KEY, FIRST_NAME VARCHAR(1024), MIDDLE_NAME VARCHAR(1024), LAST_NAME VARCHAR(1024), PREFIX VARCHAR(1024), SUFFIX VARCHAR(1024), EMAIL_ADDRESS VARCHAR(1024) UNIQUE , PHONE VARCHAR(1024), PASSWORD VARCHAR(1024), JOB_TITLE VARCHAR(1024), DEPARTMENT VARCHAR(1024), CITY VARCHAR(1024), STATE VARCHAR(1024), INST_COMPANY VARCHAR(1024), INST_COMPANY_WEBSITE VARCHAR(1024), WEBSITE VARCHAR(1024), BIO VARCHAR(1024), PREFERRED_PUB_NAME VARCHAR(1024), REGISTRATION_STATUS VARCHAR(1024), ROLES VARCHAR(1024), EXTERNAL_STORAGE_LINKED VARCHAR(1024), DROPBOX_APP_KEY VARCHAR(1024), DROPBOX_APP_SECRET VARCHAR(1024))
